### ISSUE TITLE
VITA API doc says 'site' for all sites, should be 'sites'

### ISSUE THREAD

**Issue by coxthepilot** [coxthepilot/vitasa#17]
The docs.md says the get for all sites is {end point}/site and should be .../sites

**Comment by Klaital** [comment]
Good catch. Do you want `/site` added, or just the docs updated?

**Comment by coxthepilot** [comment]
Let's just update the docs.

**Comment by Klaital** [comment]
Turns out I also had /user instead of /users in that section. I've updated both, plus the API schemas.
