### ISSUE TITLE
Decide on the data type for lat/lon

### ISSUE THREAD

**Issue by Klaital** [coxthepilot/vitasa#2]
Boto3's DynamoDB module refuses to serialize Float types into dynamo's numeric type - it requires the use of `lat = Decimal('175.1')` instead of just `lat = 175.1`

However, python3's json module refuses to serialize Decimal objects. It requires Float, and needs some hackery to make `json.dumps` work with dicts that include a Decimal field.

https://stackoverflow.com/questions/1960516/python-json-serialize-a-decimal-object

Both ways require useless hackery to make them work for common use cases, so I've downgraded the `latitude` and `longitude` fields to strings for now.

**Comment by coxthepilot** [comment]
I think we will have to settle for strings. We should probably require that the app verify ability to convert to float and decimal before confirming a site location.

**Comment by Klaital** [comment]
We can certainly enforce constraints on the value of the strings at the API layer. That's the direction I'm leaning for now.

When I add value validation on the value of the latitude and longitude strings, I'll close this issue.
