### ISSUE TITLE
Post on root URL also did a login

### ISSUE THREAD

**Issue by coxthepilot** [coxthepilot/vitasa#21]
A post on vitasa.abandonedfactory.net without the /login also did a login. Was that expected?

**Comment by Klaital** [comment]
Unable to reproduce.

    chris@klaital:~/share/devel/vitasa-web$ curl -X POST -H "Accept: application/json" -d '{"email":"kenkaku@gmail.com","password":"xxxx"}' http://vitasa.abandonedfactory.net/
    {"status":404,"error":"Not Found"}
    chris@klaital:~/share/devel/vitasa-web$ curl -X POST -H "Accept: application/json" -d '{"email":"kenkaku@gmail.com","password":"xxxx"}' http://vitasa.abandonedfactory.net/login
    {"message":"Login successful"}

I did a quick look in the logs, and mostly see calls to `POST /login`. The only call I see to `POST /` is the one I executed just now when testing. Can you verify which endpoint you were hitting?

**Comment by coxthepilot** [comment]
Turns out the client has 2 places to put the url. If they don't match it appears to be random as to which one it picks. I've confirmed that hitting the root url does NOT do a login and returns an error (as it should).
