### ISSUE TITLE
Calendar items by Site, by date range

### ISSUE THREAD

**Issue by coxthepilot** [coxthepilot/vitasa#30]
When displaying the calendar, I need to be able to get the calendar items for a specific site (optional) or date range (optional).

**Comment by Klaital** [comment]
Summarizing our discussion... 

We need an API which will return the schedule for all sites over a specified date range. Additionally, if a valid login cookie is included, the API will indicate which days/sites the user has already signed up for.

Proposed data structure:

```json
[
  {
    "date": "2018-02-01",
    "sites": [
      {
        "slug": "the-alamo",
        "efilers_needed": 5,
        "efilers_signed_up": 2,
        "is_closed": false,
        "open": "09:00:00",
        "close": "17:00:00",
        "this_user_signup": false
      }
    ]
  }
]
```

**Comment by Klaital** [comment]
Deployed to production, and updated in swagger. Access this via 

```
GET /schedule
```

Also note that I added a field ```efilers_needed``` to the Calendar model, so that Coordinators can designate a different staffing request on individual days.
