### ISSUE TITLE
Site needs number of eFilers required

### ISSUE THREAD

**Issue by coxthepilot** [coxthepilot/vitasa#32]
Need a field in Site to specify the number of eFilers that the Site requires in order to be fully staffed.

**Comment by Klaital** [comment]
Deployed to production. The Site model now includes 7 new fields, named e.g. ```sunday_efilers```.

I also added a field called ```efilers_needed``` to the Calendar model, so that a Coordinator can alter the requested number of volunteers on a day-to-day basis if they wish.
