### ISSUE TITLE
POST to /suggestions gets 422

### ISSUE THREAD

**Issue by coxthepilot** [coxthepilot/vitasa#34]
I'm pretty sure I'm send the wrong schema. Need the swagger updated with the schema that the POST expects.

**Comment by Klaital** [comment]
The 422 response body should tell you what bit of validation is failing. If you'll attach your request/response bodies here, I can help debug.

**Comment by coxthepilot** [comment]
Well, it isn't clear that .net captures the response. If its there I can't find and neither can anyone else best I can tell. Probably some magic required.

I used the swagger to format the input, but I'm pretty sure it is missing some stuff.

string bodyjson = "{ "
                + "\"user\" : \"" + id.ToString() + "\""
                + ",\"text\" : \"" + sug.Text + "\""
		+ "}";

**Comment by coxthepilot** [comment]
Thanks for the updated swagger. Still getting a 422. New json is below. I'm not including the id since it is a new object and doesn't have an id yet.
string bodyjson = "{ "
                + "\"subject\" : \"" + sug.Subject + "\""
                + ",\"details\" : \"" + sug.Text + "\""
                + ",\"status\" : \"" + sug.Status.ToString() + "\""
		+ ",\"from_public\" : \"" + "false" + "\""
                + ",\"user\" : \"" + sug.UserId.ToString() + "\""
		+ "}";
