### ISSUE TITLE
Item in work_history and work_intents needs user id

### ISSUE THREAD

**Issue by coxthepilot** [coxthepilot/vitasa#37]
Doesn't the work item need a pointer to the user? Otherwise the site only knows that someone is signed up.

**Comment by coxthepilot** [comment]
In the SCVolunteers screen, I list the work intents for a given date at a site and need to show the user's name so the Site Coordinator can approve the hours.

**Comment by Klaital** [comment]
This is already available in production. I've updated the swagger to reflect the correct schema.
