### ISSUE TITLE
Calendar exception delete errors

### ISSUE THREAD

**Issue by coxthepilot** [coxthepilot/vitasa#40]
Calendar exception create and update work as expected. Delete is returning 400 bad request. There is no entry in the swagger for the Delete so I had to guess a bit on the format. Looks like the url is /sites/{slug}/calendars/{id}

I'm passing an empty json array as the payload.

**Comment by Klaital** [comment]
I see at least one valid request in the prod logs. I'm not logging which user was logged in for each request, but it looks like you have the syntax correct here.

In general, you don't need to send any request body for GET and DELETE operations - those get their information solely from the path and query string.

```json
{
	"method": "DELETE",
	"path": "/sites/cody-library/calendars/2",
	"format": "json",
	"controller": "CalendarsController",
	"action": "destroy",
	"status": 204,
	"duration": 13.33,
	"view": 0.0,
	"db": 5.2,
	"time": "2017-09-03T18:52:54.110-07:00",
	"params": {
		"controller": "calendars",
		"action": "destroy",
		"site_id": "cody-library",
		"id": "2",
		"calendar": {}
	},
	"cookie": "[FILTERED]",
	"@timestamp": "2017-09-04T01:52:54.124Z",
	"@version": "1",
	"message": "[204] DELETE /sites/cody-library/calendars/2 (CalendarsController#destroy)"
}
```
