### ISSUE TITLE
Update on /signups fails

### ISSUE THREAD

**Issue by coxthepilot** [coxthepilot/vitasa#42]
Doing a PUT on /signups/{id} with Approved = true and Hours = 8
Call succeeds without error but the values returned do not reflect the new values

Body as input: { "approved" : "true","hours" : "8","user_id" : "6"}

Response: {"id":7,"date":"2017-09-08","created_at":"2017-09-04T22:46:58.000Z","updated_at":"2017-09-04T22:46:58.000Z","hours":0.0,"approved":false,"site":"cody-library","user":6}

When I later pull the user details that contains this work item, the values for approved are still false and hours = 0.0, so I'm assuming the write didn't stick.

I note that the updated time is still the create time, ie no change.

**Comment by Klaital** [comment]
Sure enough, those fields were missing from the whitelist. Fixed in production.
