### ISSUE TITLE
Need GET/users/{id} to include Site Coordinator sites

### ISSUE THREAD

**Issue by coxthepilot** [coxthepilot/vitasa#45]
When I get user details for a Site Coordinator, would like to also get a list of siteSlug and Site names for which that user is the Site Coordinator. Saves me another API call in the login process.

**Comment by Klaital** [comment]
What about Backup Coordinators?

**Comment by coxthepilot** [comment]
Yes, need them too...

**Comment by Klaital** [comment]
Done. This is a new field on GetUserDetails called ```sites_coordinated```, and includes all sites that the user is either Coordinator or Backup for.
