### ISSUE TITLE
Add Descriptive Site Status

### ISSUE THREAD

**Issue by Klaital** [coxthepilot/vitasa#5]
We need a site status: closed, open and accepting clients, open but close to the limit, open but no longer accepting new clients.

I propose this as a new field, to be added to schema/site.json

    "site_status": {
        "type": "string",
        "enum": [ "open", "closed", "accepting", "near_limit", "not_accepting" ]
    }

Alternatively, we already have a field for `is_open`. Should this new field just describe the "fullness" of the site? Is it better to have this merged into one field, or two separate?

We could convert `is_open` to a string, and use this enum for the Site Coordinator to set as the current status. Thoughts?

**Comment by coxthepilot** [comment]
Suggest we move to the enum site status and eliminate the is_open since that enumeration is the purpose of the app.

**Comment by Klaital** [comment]
fixed in klaital/vitasa-web@c6474e7d7d5a833a243faea4a5277fc116091a63

Deployed in staging (vitasa.klaital.com).
