### ISSUE TITLE
POST on /resources gets a 422

### ISSUE THREAD

**Issue by coxthepilot** [coxthepilot/vitasa#51]
Did a POST on /resources with the following and got a error 422

{ "slug" : "about-this-app","text_en" : "English English","text_es" : "Espanol Espanol "}

No "\n" or unicode in this one. A GET on that slug returns a 404 (as expected). I'm not adding the accept-language header on this POST.

**Comment by Klaital** [comment]
Fixed in production. I'd forgotten to disable CSRF token checks for the new Resources Controller.
