### ISSUE TITLE
Need a list added to Site

### ISSUE THREAD

**Issue by coxthepilot** [coxthepilot/vitasa#52]
I need to keep track of the capabilities of a site. A site could have 0..all of these.

Capability: Drop-off, Express, MFT

Should be just a list as a field on Site

**Comment by Klaital** [comment]
I propose an array field ```features```, for both post and get requests, each element of which must be a valid member of an enum. Essentially the same behavior as user roles.

**Comment by Klaital** [comment]
Renamed ```Drop-off``` to ```DropOff``` and deployed to production.
