### ISSUE TITLE
Error 500 on send notification

### ISSUE THREAD

**Issue by coxthepilot** [coxthepilot/vitasa#62]
Message for the notification created just fine; on the send, got an error 500 (server internal error).

**Comment by coxthepilot** [comment]
Happens on send and resend; only error info I can se through the api is error 500

**Comment by Klaital** [comment]
Error was `Aws::Errors::MissingCredentialsError: unable to sign request without credentials set`

Apparently we never tested notification sending after the migration to Digital Ocean, and I never copied over the AWS credentials required to make the SNS API calls. 

I've copied the credentials over and restarted the application server.
