### ISSUE TITLE
Automatically update the API Gateway Models from git schemas

### ISSUE THREAD

**Issue by Klaital** [coxthepilot/vitasa#7]
In AWS's API Gateway, we can define the expected request and response schemas for our APIs, by creating a Model, and associating it with the Method Request or Method Response.

This means I'm now maintaining a schema file here in git, as well as a version that I think AWS will be validating the API responses against. 

We need to build some tooling to automatically upload the files in `docs/schemas` to the API Gateway Models. I'm sure there's an AWS API to call for this, but I haven't done the research yet.

For that matter, I need to write tests that will validate that the APIs actually conform to the given schemas. Ideally that test should run before a commit is allowed, or at least automatically after a git push.

**Comment by coxthepilot** [comment]
Irrelevant since are no longer utilizing Lambda.
